version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    
  app:
    build: .
    container_name: express_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db  
      DB_USER: root
      DB_PASSWORD: faculdade
      DB_NAME: testdb
    networks: 
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
